[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- KRYTYCZNE DLA N16R8 (Wymuszenie magistrali Octal SPI dla PSRAM) ---
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

; --- FLAGI KOMPILATORA (Aktywacja PSRAM) ---
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -O2
    -DCORE_DEBUG_LEVEL=3

; --- BIBLIOTEKI ---
lib_deps = 
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.1
    earlephilhower/ESP8266Audio @ ^1.9.7
    mathieucarbou/ESPAsyncWebServer @ ^3.3.22